apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: apps
  labels:
    app: auth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
      - name: auth-api
        image: saarwasserman/dinghy-auth-api:0.1.0
        imagePullPolicy: Always
        env:
          - name: AUTH_DB_DSN
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: auth_db_dsn
        command: 
          - ./bin/api
          - -port=40020
          - -cors-trusted-origins="http://localhost:3000"
          - -notifications-service-host=notifications-api.apps.svc.cluster.local
          - -notifications-service-port=40010
          - -cache-endpoint=redis-svc.redis.svc.cluster.local:6379
        ports:
        - containerPort: 40020
        resources:
          limits:
            memory: "2Gi"
            cpu: "500m"
            ephemeral-storage: "2Gi"
          requests:
            ephemeral-storage: "1Gi"
            cpu: "500m"
            memory: "250Mi"
